config/routes.rb
Firehoseapp::Application.routes.draw do

   root 'static_pages#index'
   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index

		@pics = Pic.all

	end

	def new
		@pic = Pic.new
	end

	def create
			Pic.create( pic_params)
			redirect_to pics_path
	end

	private

	def pic_params
		params.require(:pic).permit(:lesson, :emotion, :learned, :picture);
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Firehoseapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <!-- part of original code removed: <a class="brand" href="#">Friar Hose App</a> -->
    <%= link_to 'Friar Hose App', root_path, :class=> 'brand'  %>

    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
            <li>
                <%= link_to 'Submit Your Pic!', new_pic_path  %>

            </li>
            <li>
                <%= link_to 'See Submissions', pics_path  %>

            </li>

        </ul>




    </div>
     
    </div>
    </div>
    </div>	

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	<div class="fishbox span4" text-center>
		<h1 class="custom-h1">
			Lesson: <%= pic.lesson %>
		</h1>
		<br />
		
		<%= image_tag pic.picture %>
		<br />
		<h2>
			Emotion: <%= pic.emotion %>
			<br />
			<br />
			Learned: <%= pic.learned %>
		</h2>
	</div>
<% end %>

app/views/pics/new.html.erb
<div class="fishbox span6 offset3 text-center">
	<h1 class="custom-h1" > <!-- class="custom-h1"  -->

		Submit Your Pic!
	</h1>

	<h2>
		<%= simple_form_for @pic do|f| %>
			<%= f.input :lesson, label: 'Lesson #:' %>
			<br />

			<%= f.input :emotion, label: 'How did you feel?', placeholder: "Happy, Stoked, Excited, Super Duper, etc." %>
			<br />

			<%= f.input :learned, label: 'What did you learn?', placeholder: "HTML, CSS3, Rails, Ruby, Github, how to jump higher, etc." %>
			<br />

			<%= f.input :picture, label: "Upload a pretty picture"%>
			<br />

			<%= f.button :submit, 'Submit!', :class => 'btn-large btn btn-info' %>
			

			
			
		<% end %>
	</h2>
</div>

app/views/static_pages/index.html.erb
<div class = "fishbox span7 offset3">

	<h1 class="custom-h1 text-center">

		LJ: "Turn your music downnnn!"

	</h1>
	<br><br />
	<h2>

		Question: What did Ted reply to LJ?
		<br />
		<br />
		"Little John, turn down for whatttt? <br />
		I'm just getting started."
		<br />
		<br />
		This file index.html.erb is in views -> static_pages

	</h2>

	<h2 class="text-center">
	<%= link_to 'Launch', new_pic_path, :class => 'btn-large btn btn-info' %>
	</h2>
	
</div>